version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      LEVEL: "mundos"
      VERSION: "1.21.10"
    volumes:
      - ./minecraft/data:/data
      - ./minecraft/mundos:/data/mundos
    restart: always
