version: "3.9"

services:
  metube:
    image: alexta69/metube:latest
    container_name: metube
    volumes:
      - ./downloads:/downloads
      - ./audio-downloads:/audio-downloads
    environment:
      - UID=1000
      - GID=1000
      - TZ=America/Sao_Paulo
    ports:
      - "8082:8081"
    restart: unless-stopped