services:
  metube:
    image: alexta69/metube:latest
    container_name: metube
    ports:
      - '8004:8081'
    volumes:
      - ./downloads:/downloads
      - ./audio-downloads:/audio-downloads # Optional, if you want to separate audio downloads
    environment:
      - UID=1000
      - GID=1000
      - TZ=Asia/Kolkata
      - AUDIO_DOWNLOAD_DIR=/audio-downloads # Optional, if you want to separate audio downloads
    restart: unless-stopped
